name: geeta2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.11.1
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.7
  url_launcher: ^6.2.6
  audioplayers: ^6.5.1
  http: ^1.6.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/media/icon1.jpg"

  # Optional adaptive icon
  # adaptive_icon_foreground: "assets/media/icon1.jpg"
  # adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/media/
    - assets/media/flute.mp3

  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/yourfont.ttf